name: Deploy Apps Script (Dev & Prod)

on:
  push:
    branches:
      - dev
      - prod

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install clasp globally
        run: npm install -g @google/clasp

      - name: Authenticate clasp
        env:
          CLASPRC: ${{ secrets.CLASPRC_JSON }}
        run: |
          echo "$CLASPRC" | base64 --decode > ~/.clasprc.json
          chmod 600 ~/.clasprc.json

      - name: Copy correct clasp config for Dev
        run: |
          cp src/.clasp.dev.json .clasp.json

      - name: Deploy to Dev
        run: clasp push --force

  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install clasp globally
        run: npm install -g @google/clasp

      - name: Authenticate clasp
        env:
          CLASPRC: ${{ secrets.CLASPRC_JSON }}
        run: |
          echo "$CLASPRC" | base64 --decode > ~/.clasprc.json
          chmod 600 ~/.clasprc.json

      - name: Copy correct clasp config for Prod
        run: |
          cp src/.clasp.prod.json .clasp.json

      - name: Deploy to Prod
        run: clasp push --force

      - name: Version & Deploy Prod Release
        run: |
          clasp version "Prod release - ${{ github.sha }}"
          clasp deploy