jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, main]

    if: ${{ (github.ref == 'refs/heads/dev' && matrix.environment == 'dev') || (github.ref == 'refs/heads/main' && matrix.environment == 'main') }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install clasp globally
        run: npm install -g @google/clasp

      - name: Authenticate clasp
        env:
          CLASPRC: ${{ secrets.CLASPRC_JSON }}
        run: |
          echo "$CLASPRC" | base64 --decode > ~/.clasprc.json
          chmod 600 ~/.clasprc.json

      - name: Copy correct clasp config
        run: |
          cp src/.clasp.${{ matrix.environment }}.json .clasp.json

      - name: Deploy
        run: clasp push --force

      - name: Version & Deploy main Release
        if: ${{ matrix.environment == 'main' }}
        run: |
          clasp version "main release - ${{ github.sha }}"
          clasp deploy