name: Deploy Apps Script (Dev & Prod)

on:
  push:
    branches:
      - dev
      - prod

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install clasp globally
        run: npm install -g @google/clasp

      - name: Authenticate clasp
        env:
          CLASPRC: ${{ secrets.CLASPRC_JSON }}
        run: |
          echo "$CLASPRC" | base64 --decode > ~/.clasprc.json
          # Ensure the file has the correct permissions
          chmod 600 ~/.clasprc.json
          # Display a sanitized version to check format (hide sensitive data)
          grep -v "token\|api_key" ~/.clasprc.json || echo "Failed to create clasprc file"

      - name: Debug - List files
        run: |
          ls -la src/
          ls -la src/.clasp* || echo "No .clasp files found in src"

      - name: Copy correct clasp config for Dev
        run: |
          cp src/.clasp.dev.json src/.clasp.json

      - name: Deploy to Dev
        run: |
          # Execute clasp commands in the src directory while using the global auth
          cd src
          clasp push --force

  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install clasp globally
        run: npm install -g @google/clasp

      - name: Authenticate clasp
        env:
          CLASPRC: ${{ secrets.CLASPRC_JSON }}
        run: |
          echo "$CLASPRC" | base64 --decode > ~/.clasprc.json
          # Ensure the file has the correct permissions
          chmod 600 ~/.clasprc.json
          # Display a sanitized version to check format (hide sensitive data)
          grep -v "token\|api_key" ~/.clasprc.json || echo "Failed to create clasprc file"

      - name: Debug - List files
        run: |
          ls -la src/
          ls -la src/.clasp* || echo "No .clasp files found in src"

      - name: Copy correct clasp config for Prod
        run: |
          cp src/.clasp.prod.json src/.clasp.json

      - name: Deploy to Prod
        run: |
          cd src
          clasp push --force

      - name: Version & Deploy Prod Release
        run: |
          cd src
          clasp version "Prod release - ${{ github.sha }}"
          clasp deploy